[2022-11-14 02:07:43,076] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: pyspark_bmi.load_data 2022-11-13T12:00:00+00:00 [queued]>
[2022-11-14 02:07:43,091] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: pyspark_bmi.load_data 2022-11-13T12:00:00+00:00 [queued]>
[2022-11-14 02:07:43,092] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2022-11-14 02:07:43,092] {taskinstance.py:1018} INFO - Starting attempt 3 of 3
[2022-11-14 02:07:43,092] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2022-11-14 02:07:43,099] {taskinstance.py:1038} INFO - Executing <Task(PythonOperator): load_data> on 2022-11-13T12:00:00+00:00
[2022-11-14 02:07:43,103] {standard_task_runner.py:51} INFO - Started process 23892 to run task
[2022-11-14 02:07:43,106] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'pyspark_bmi', 'load_data', '2022-11-13T12:00:00+00:00', '--job-id', '12', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/pyspark_bmi.py', '--cfg-path', '/tmp/tmpr1_1b6mu']
[2022-11-14 02:07:43,109] {standard_task_runner.py:76} INFO - Job 12: Subtask load_data
[2022-11-14 02:07:43,153] {logging_mixin.py:103} INFO - Running <TaskInstance: pyspark_bmi.load_data 2022-11-13T12:00:00+00:00 [running]> on host 6f0683b4a09b
[2022-11-14 02:07:43,190] {taskinstance.py:1232} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=pyspark_bmi
AIRFLOW_CTX_TASK_ID=load_data
AIRFLOW_CTX_EXECUTION_DATE=2022-11-13T12:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=backfill__2022-11-13T12:00:00+00:00
[2022-11-14 02:07:43,464] {logging_mixin.py:103} INFO -    Gender  Height  Weight  Index        imc             Criterio
0    Male     174      96      4  31.708284      Obesidad severa
1    Male     189      87      2  24.355421               Normal
2    Male     149      61      3  27.476240        Obesidad leve
3    Male     189     104      3  29.114526        Obesidad leve
4    Male     147      92      5  42.574853  Obesidad muy severa
5    Male     154     111      5  46.803846  Obesidad muy severa
6    Male     174      90      3  29.726516        Obesidad leve
7    Male     195      81      2  21.301775               Normal
8    Male     155      51      2  21.227888               Normal
9    Male     191      79      2  21.655108               Normal
10   Male     140     129      5  65.816327  Obesidad muy severa
11   Male     144     145      5  69.926698  Obesidad muy severa
12   Male     172     139      5  46.984857  Obesidad muy severa
13   Male     157     110      5  44.626557  Obesidad muy severa
14   Male     185     139      5  40.613587  Obesidad muy severa
15   Male     190      95      3  26.315789        Obesidad leve
16   Male     187      62      1  17.729989            Bajo peso
17   Male     179     152      5  47.439219  Obesidad muy severa
18   Male     153     121      5  51.689521  Obesidad muy severa
19   Male     178      52      1  16.412069            Bajo peso
[2022-11-14 02:07:43,465] {python.py:118} INFO - Done. Returned value was: None
[2022-11-14 02:07:43,475] {taskinstance.py:1142} INFO - Marking task as SUCCESS. dag_id=pyspark_bmi, task_id=load_data, execution_date=20221113T120000, start_date=20221114T020743, end_date=20221114T020743
[2022-11-14 02:07:43,499] {taskinstance.py:1195} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-11-14 02:07:43,517] {local_task_job.py:118} INFO - Task exited with return code 0
[2022-11-14 03:41:31,602] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: pyspark_bmi.load_data 2022-11-13T12:00:00+00:00 [queued]>
[2022-11-14 03:41:31,619] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: pyspark_bmi.load_data 2022-11-13T12:00:00+00:00 [queued]>
[2022-11-14 03:41:31,619] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2022-11-14 03:41:31,619] {taskinstance.py:1018} INFO - Starting attempt 3 of 3
[2022-11-14 03:41:31,619] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2022-11-14 03:41:31,628] {taskinstance.py:1038} INFO - Executing <Task(PythonOperator): load_data> on 2022-11-13T12:00:00+00:00
[2022-11-14 03:41:31,633] {standard_task_runner.py:51} INFO - Started process 10032 to run task
[2022-11-14 03:41:31,636] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'pyspark_bmi', 'load_data', '2022-11-13T12:00:00+00:00', '--job-id', '10', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/pyspark_bmi.py', '--cfg-path', '/tmp/tmp_p7qmy6w']
[2022-11-14 03:41:31,639] {standard_task_runner.py:76} INFO - Job 10: Subtask load_data
[2022-11-14 03:41:31,683] {logging_mixin.py:103} INFO - Running <TaskInstance: pyspark_bmi.load_data 2022-11-13T12:00:00+00:00 [running]> on host 676a9425fa5f
[2022-11-14 03:41:31,720] {taskinstance.py:1232} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=pyspark_bmi
AIRFLOW_CTX_TASK_ID=load_data
AIRFLOW_CTX_EXECUTION_DATE=2022-11-13T12:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=backfill__2022-11-13T12:00:00+00:00
[2022-11-14 03:41:31,875] {taskinstance.py:1396} ERROR - FATAL:  database "example" does not exist
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1086, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1260, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1300, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 117, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 128, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/pyspark_bmi.py", line 77, in load_data_to_postgresql
    port="5432"
  File "/home/airflow/.local/lib/python3.6/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  database "example" does not exist

[2022-11-14 03:41:31,877] {taskinstance.py:1440} INFO - Marking task as FAILED. dag_id=pyspark_bmi, task_id=load_data, execution_date=20221113T120000, start_date=20221114T034131, end_date=20221114T034131
[2022-11-14 03:41:31,928] {local_task_job.py:118} INFO - Task exited with return code 1
